CodeRelease 2021

diff --git a/Install/createRobot b/Install/createRobot
--- a/Install/createRobot
+++ b/Install/createRobot
@@ -21,31 +21,35 @@ profilesOnly=""
 ip=""
 head=""
 body=""
+lansubnet="192.168"
+wlansubnet="10.0"
 
 usage() {
   echo "usage:"
   echo "${0} [-h]"
-  echo "${0} [-d] [-t <team>] -r <robot> -i <ip> <name>"
-  echo "${0} [-d] [-t <team>] -r <robot> -s <head> -b <body> <name>"
-  echo "${0} -p [-t <team>] -r <robot> <name>"
+  echo "${0} [-d] [-t <team>] -r <robot> -i <ip> [-l <subnet>] [-w <subnet>] <name>"
+  echo "${0} [-d] [-t <team>] -r <robot> -s <head> -b <body> [-l <subnet>] [-w <subnet>] <name>"
+  echo "${0} -p [-t <team>] -r <robot> [-l <subnet>] [-w <subnet>] <name>"
   echo "${0} -D <name>"
   echo ""
-  echo " <name> : name of the robot"
-  echo " <team> : the third number of the IPv4 address of the robot (same for all robots)"
-  echo " <robot>: the last number of the IPv4 address of the robot (different for all robots)"
-  echo " <ip>   : Retrieve serial numbers from the robot with the given ip address"
-  echo " <head> : Specify serial numbers of the robot's head"
-  echo " <body> : Specify serial numbers of the robot's body"
+  echo " <name>     : name of the robot"
+  echo " <team>     : the third number of the IPv4 address of the robot (same for all robots)"
+  echo " <robot>    : the last number of the IPv4 address of the robot (different for all robots)"
+  echo " <ip>       : Retrieve serial numbers from the robot with the given ip address"
+  echo " <head>     : Specify serial numbers of the robot's head"
+  echo " <body>     : Specify serial numbers of the robot's body"
   echo ""
-  echo " -d     : Delete existing files for the given robot before creating new files"
-  echo " -D     : Only delete all files for the given robot"
-  echo " -p     : Only update the network profiles"
-  echo " -h     : Display this help"
+  echo " -d         : Delete existing files for the given robot before creating new files"
+  echo " -D         : Only delete all files for the given robot"
+  echo " -p         : Only update the network profiles"
+  echo " -l <subnet>: Set lan subnet"
+  echo " -w <subnet>: Set wireless lan subnet"
+  echo " -h         : Display this help"
   exit 1
 }
 
 parseOptions() {
-  while getopts :hpt:r:Ddi:s:b: opt ; do
+  while getopts :hpt:r:Ddi:s:b:l:w: opt ; do
     case "$opt" in
       p)
         profilesOnly="true"
@@ -71,6 +75,12 @@ parseOptions() {
       b)
         body="$OPTARG"
         ;;
+      l)
+        lansubnet="$OPTARG"
+        ;;
+      w)
+        wlansubnet="$OPTARG"
+        ;;
       [?]|h)
         usage
         ;;
@@ -88,8 +98,6 @@ parseOptions() {
 
   robotName=${1}
 
-  robotDir="${baseDir}/Robots/${robotName}"
-
   if [ -z ${deleteOnly} ]; then
     if [ -z "${teamID}" -o -z "${robotPart}" -o -z "${robotName}" ]; then
       usage
@@ -102,7 +110,6 @@ parseOptions() {
   fi
 
   debug "robotName: " "${robotName}"
-  debug "robotDir: " "${robotDir}"
   debug "teamID: " "${teamID}"
   debug "robotPart: " "${robotPart}"
   debug "ip: " "${ip}"
@@ -142,8 +149,6 @@ function checkFile()
 function checkFiles()
 {
   foundFiles=""
-  checkFile "${robotDir}/hostname"             || foundFiles="true"
-  checkFile "${robotDir}"                      || foundFiles="true"
   checkFile "${configDir}/Robots/${robotName}" || foundFiles="true"
   debug "foundFiles: ${foundFiles}"
 
@@ -153,29 +158,6 @@ function checkFiles()
   fi
 }
 
-function createRobotDirectory()
-{
-  message "Creating robot directory"
-  mkdir -p "${robotDir}" || return 1
-  return 0
-}
-
-function createHostname()
-{
-  echo "${robotName}" > "${robotDir}/hostname"
-  return 0;
-}
-
-function createProfiles()
-{
-  message "Creating network profiles"
-  mkdir -p "${profileDir}"
-
-  sed -e "s/%teamID%/${teamID}/g" -e "s/%robotPart%/${robotPart}/g" <"${networkDir}/wired.service" >"${robotDir}/wired.service" || return 1
-  sed -e "s/%teamID%/${teamID}/g" -e "s/%robotPart%/${robotPart}/g" <"${networkDir}/wireless.service" >"${robotDir}/wireless.service" || return 1
-  return 0
-}
-
 function createCalibrationDirectory()
 {
   message "Creating calibration directory"
@@ -183,13 +165,13 @@ function createCalibrationDirectory()
   return 0
 }
 
-function createBushConfig()
+function createNetworkConfig()
 {
   message "Creating network.cfg"
 cat > "${configDir}/Robots/$robotName/network.cfg" << EOF
 name = "${robotName}";
-lan = "192.168.${teamID}.${robotPart}";
-wlan = "10.0.${teamID}.${robotPart}";
+lan = "${lansubnet}.${teamID}.${robotPart}";
+wlan = "${wlansubnet}.${teamID}.${robotPart}";
 EOF
 }
 
@@ -222,18 +204,12 @@ checkApp "sed" "stream editor"
 parseOptions "$@"
 
 if [ -n "${profilesOnly}" ]; then
-  if ! [ -d ${robotDir} ]; then
+  if ! [ -d "${configDir}/Robots/${robotName}" ]; then
     error "Robot '${robotName}' does not exist"
     fatal "Rerun ${0} without -p"
   fi
-
-  if ! createProfiles; then
-    error "Failed to create network profiles"
-    fatal "Rerun ${0} with -d"
-  fi
-
-  if ! createBushConfig; then
-    error "Failed to create configuration for the bush"
+  if ! createNetworkConfig; then
+    error "Failed to create network configuration"
     fatal "Rerun ${0} with -d"
   fi
 else
@@ -252,24 +228,12 @@ else
     elif [ -z "$head" -o -z "$body" ]; then
       fatal "Both serial numbers must be specified"
     fi
-    if ! createRobotDirectory; then
-      error "Failed to create robot directory"
-      fatal "Rerun ${0} with -d"
-    fi
-    if ! createHostname; then
-      error "Failed to create hostname"
-      fatal "Rerun ${0} with -d"
-    fi
-    if ! createProfiles; then
-      error "Failed to create network profiles"
-      fatal "Rerun ${0} with -d"
-    fi
     if ! createCalibrationDirectory; then
       error "Failed to create calibration directory"
       fatal "Rerun ${0} with -d"
     fi
-    if ! createBushConfig; then
-      error "Failed to create configuration for the bush"
+    if ! createNetworkConfig; then
+      error "Failed to create network configuration"
       fatal "Rerun ${0} with -d"
     fi
     createRobotsFile
diff --git a/Make/Common/copyLogs b/Make/Common/copyLogs
--- a/Make/Common/copyLogs
+++ b/Make/Common/copyLogs
@@ -10,14 +10,25 @@ basePath=$(cd "$(dirname "$(which "$0")")" && pwd)
 usage()
 {
   echo "usage: $0 [-d | --just-delete] [<targetDir>]" >&2
-  echo " -d             Delete log files after copying." >&2
-  echo " --just-delete  Just delete log files." >&2
+  echo "  options:"
+  echo "    -d             Delete log files after copying." >&2
+  echo "    --just-delete  Just delete log files." >&2
+  echo "  examples:"
+  echo "    $0"
+  echo "    $0 -d ../../Config/Logs"
+  echo "    $0 sftp://user@host:/path"
+  echo "    $0 --just-delete"
   exit 1
 }
 
 copy=true
 delete=false
 targetDir=${basePath}/../../Config/Logs
+mkdir1=
+mkdir2="xargs mkdir -p"
+cp1=
+cp2="xargs cp"
+cmd=xargs
 while true; do
   case $1 in
     "")
@@ -39,6 +50,14 @@ while true; do
       ;;
     *)
       targetDir=$1
+      if [ ! -z "$(grep <<<"$targetDir" "^sftp://.*:")" ]; then
+        host="$(sed <<<"$targetDir" "s%^sftp://\([^:]*\).*%\1%")"
+        targetDir="$(sed <<<"$targetDir" "s%^sftp://[^:]*:%%")"
+        mkdir1="-mkdir"
+        mkdir2="sftp -qb - $host"
+        cp1=put
+        cp2="sftp -qb - $host"
+      fi
       ;;
   esac
   shift
@@ -46,22 +65,34 @@ done
 
 set -eu
 
-files=$(ls /mnt/*_B-HUMAN/logs/*_*_*.log /media/*_B-HUMAN/logs/*_*_*.log /media/$USER/*_B-HUMAN/logs/*_*_*.log /cygdrive/*/logs/*_*_*.log /Volumes/*_B-HUMAN/logs/*_*_*.log 2>/dev/null || true)
+targetPath="$targetDir/$(date +%F-%H-%M)"
+
+files=$(ls /mnt/*_B-HUMAN/logs/*_*_*.log /media/*_B-HUMAN/logs/*_*_*.log /media/$USER/*_B-HUMAN/logs/*_*_*.log /run/media/$USER/*_B-HUMAN/logs/*_*_*.log /cygdrive/*/logs/*_*_*.log /Volumes/*_B-HUMAN/logs/*_*_*.log 2>/dev/null || true)
 
 if [ $copy = true -a ! -z "$files" ]; then
-  targetPath="$targetDir/$(date +%F-%H-%M)"
-  mkdir -p "$targetPath"
+  echo "$mkdir1 \"$targetPath\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
   while read path; do
     if [ ! -z "$path" ]; then
-      echo "Copying logs from $(dirname "$path") ..."
+      echo "Copying $path ..."
       name=$(basename $path | sed "s%_.*%%")
-      mkdir -p "$targetPath/$name"
-      cp "$path" "$targetPath/$name/"
-      if [ ! -z "$(ls "$(dirname "$path")"/bhumand* 2>/dev/null || true)" ]; then
-        cp "$(dirname "$path")"/bhumand* "$targetPath/$name/"
-      fi
+      echo "$mkdir1 \"$targetPath/$name\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
+      echo "$cp1 \"$path\"" "\"$targetPath/$name/\"" | $cp2 >/dev/null
     fi
   done <<<"$files"
+fi
+
+files2=$(ls /mnt/*_B-HUMAN/logs/bhumand*.log /media/*_B-HUMAN/logs/bhumand*.log /media/$USER/*_B-HUMAN/logs/bhumand*.log /run/media/$USER/*_B-HUMAN/logs/bhumand*.log /cygdrive/*/logs/bhumand*.log /Volumes/*_B-HUMAN/logs/bhumand*.log 2>/dev/null || true)
+
+if [ $copy = true -a ! -z "$files2" ]; then
+  echo "$mkdir1 \"$targetPath\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
+  while read path; do
+    if [ ! -z "$path" ]; then
+      echo "Copying $path ..."
+      name="$(grep " Hi, I am " "$path" | head -1 | sed "s%[^ ]* Hi, I am \(.*\)\.%\1%")"
+      echo "$mkdir1 \"$targetPath/$name\"" | $mkdir2 2>&1 >/dev/null | ( grep -v "Couldn't create directory: Failure" 1>&2 || true )
+      echo "$cp1 \"$path\"" "\"$targetPath/$name/\"" | $cp2 >/dev/null
+    fi
+  done <<<"$files2"
 fi
 
 if $delete; then
@@ -70,5 +101,6 @@ if $delete; then
       echo "Deleting logs from $(dirname "$path") ..."
       rm "$(dirname "$path")"/*
     fi
-  done <<<"$files"
+  done <<<"$files
+$files2"
 fi
diff --git a/Make/Common/downloadLogs b/Make/Common/downloadLogs
--- a/Make/Common/downloadLogs
+++ b/Make/Common/downloadLogs
@@ -5,25 +5,25 @@ basePath=$(cd "$(dirname "$(which "$0")")" && pwd)
 
 usage()
 {
-  echo "usage: downloadLogs [-d | --just-delete] <robot name> <ip>"
+  echo "usage: downloadLogs [-d | --just-delete] <ip>"
   echo " -d            - Delete log files after download."
   echo " --just-delete - Just delete log files."
   echo "  examples:"
-  echo "    ./downloadLogs Leonard 192.168.2.28"
-  echo "    ./downloadLogs -d Leonard 192.168.2.28"
+  echo "    ./downloadLogs 192.168.2.28"
+  echo "    ./downloadLogs -d 192.168.2.28"
   exit 1
 }
 
 #Variables
 logpath="/home/nao/logs/"
-keySource="${basePath}/../../Config/Keys/id_rsa_nao"
+keySource="${basePath}/../../Install/Keys/id_rsa_nao"
 keyFile=/tmp/id_rsa_nao
-cp "${keySource}" ${keyFile}
+cp -n "${keySource}" ${keyFile}
 sshoptions="-c aes128-ctr -i ${keyFile} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"
 
 chmod 600 $keyFile
 
-if [ $# -lt 2 ]
+if [ $# -lt 1 ]
 then
   usage
 fi
@@ -32,28 +32,31 @@ if [ "$1" = "-d" ]
 then
     download=true
     delete=true
-    name=$2
-    ip=$3
+    ip=$2
 elif [ "$1" = "--just-delete" ]
 then
     download=false
     delete=true
-    name=$2
-    ip=$3
+    ip=$2
 else
     download=true
     delete=false
-    name=$1
-    ip=$2
+    ip=$1
 fi
 
 if $download
 then
+  name=`ssh $sshoptions -o ConnectTimeout=2 nao@$ip "hostname"`
+  if [ -z "$name" ]
+  then
+    echo "Could not get name from robot."
+    exit 1
+  fi
   localLogpath=${BHUMAN_LOG_DIR:="${basePath}/../../Config/Logs"}/$(date +%F-%H-%M)/$name
 
   #check if log file dir exists
   if [ ! -d "$localLogpath" ]; then
-      mkdir -p "$localLogpath"
+    mkdir -p "$localLogpath"
   fi
 
   #check if log dir exist on the remote robot
@@ -61,15 +64,15 @@ then
   logPathExists=$?
   if [ "$logPathExists" -ne 0 ]
   then
-      echo "Logfile directory does not exist on robot."
-      exit 1
+    echo "Logfile directory does not exist on robot."
+    exit 1
   fi
 
   #check if log directory is not empty
   LOGS=`ssh $sshoptions nao@$ip "ls $logpath | grep .log"`
   if [ -z "$LOGS" ]; then
-      echo "No log files on robot."
-      exit 1
+    echo "No log files on robot."
+    exit 1
   fi
 fi
 
@@ -77,7 +80,7 @@ PROCESSES=`ssh $sshoptions nao@$ip "pgrep bhuman"`
 if [ ! -z "$PROCESSES" ]; then
   RESTART=1
   echo "stopping bhuman"
-  ssh $sshoptions nao@$ip "bhumand stop > /dev/null"
+  ssh $sshoptions nao@$ip "systemctl --user stop bhuman.service > /dev/null"
 fi
 
 if $download
@@ -115,12 +118,12 @@ fi
 
 if $delete
 then
-    #remove log files from robot
-    echo "Deleting log files from robot"
-    ssh $sshoptions nao@$ip "rm -f $logpath*"
+  #remove log files from robot
+  echo "Deleting log files from robot"
+  ssh $sshoptions nao@$ip "rm -f $logpath*"
 fi
 
 if [ ! -z $RESTART ]; then
   echo "starting bhuman"
-  ssh $sshoptions nao@$ip "bhumand start > /dev/null"
+  ssh $sshoptions nao@$ip "systemctl --user start bhuman.service > /dev/null"
 fi
diff --git a/Make/Hooks/pre-commit b/Make/Hooks/pre-commit
--- a/Make/Hooks/pre-commit
+++ b/Make/Hooks/pre-commit
@@ -9,10 +9,10 @@
 
 if 'GIT' rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+  against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+  # Initial commit: diff against an empty tree object
+  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ascii filenames set this variable to true.
@@ -22,25 +22,25 @@ allownonascii=$('GIT' config hooks.allownonascii)
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test "$('GIT' diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0')"
+  # Note that the use of brackets around a tr range is ok here, (it's
+  # even required, for portability to Solaris 10's /usr/bin/tr), since
+  # the square bracket bytes happen to fall in the designated range.
+  test "$('GIT' diff --cached --name-only --diff-filter=A -z $against |
+    LC_ALL=C tr -d '[ -~]\0')"
 then
-	echo "Error: Attempt to add a non-ascii file name."
-	echo
-	echo "This can cause problems if you want to work"
-	echo "with people on other platforms."
-	echo
-	echo "To be portable it is advisable to rename the file ..."
-	echo
-	echo "If you know what you are doing you can disable this"
-	echo "check using:"
-	echo
-	echo "  'GIT' config hooks.allownonascii true"
-	echo
-	exit 1
+  echo "Error: Attempt to add a non-ascii file name."
+  echo
+  echo "This can cause problems if you want to work"
+  echo "with people on other platforms."
+  echo
+  echo "To be portable it is advisable to rename the file ..."
+  echo
+  echo "If you know what you are doing you can disable this"
+  echo "check using:"
+  echo
+  echo "  'GIT' config hooks.allownonascii true"
+  echo
+  exit 1
 fi
 
 # If you want to forbid tab characters in files, set this variable to true.
@@ -48,29 +48,29 @@ checkTabs=$('GIT' config hooks.checkTabs)
 
 if [ "$checkTabs" = "true" ]
 then
-        # find changed files with tab characters (ignore files in Make
-        # directories)
-	filesWithTabs=""
-	for file in "$('GIT' diff --cached --name-only)"
-	do
-		if [ "$(echo "$file" | grep -E '^Src/.*')" -o "$(echo "$file" | grep -E '^Util/SimRobot/Src/.*')" ]
-		then
-			if [ "$('GIT' diff --cached --inter-hunk-context=0 -- "$file" | grep -E '^\+' | LC_ALL=C tr -d -c '\t')" ]
-			then
-				filesWithTabs="$filesWithTabs $file"
-			fi
-		fi
-	done
+  # find changed files with tab characters (ignore files in Make
+  # directories)
+  filesWithTabs=""
+  for file in "$('GIT' diff --cached --name-only)"
+  do
+    if [ "$(echo "$file" | grep -E '^Src/.*')" -o "$(echo "$file" | grep -E '^Util/SimRobot/Src/.*')" ]
+    then
+      if [ "$('GIT' diff --cached --inter-hunk-context=0 -- "$file" | grep -E '^\+' | LC_ALL=C tr -d -c '\t')" ]
+      then
+        filesWithTabs="$filesWithTabs $file"
+      fi
+    fi
+  done
         # list files with tab characters an exit with non-zero
-	if [ "${#filesWithTabs}" -gt 0 ]
-	then
-		echo "Error: Attempt to add tab characters."
-		for file in "$filesWithTabs"
-		do
-			echo "\t$file"
-		done
-		exit 1
-	fi
+  if [ "${#filesWithTabs}" -gt 0 ]
+  then
+    echo "Error: Attempt to add tab characters."
+    for file in "$filesWithTabs"
+    do
+      echo "\t$file"
+    done
+    exit 1
+  fi
 fi
 
 # check if there are trailing whitespaces
diff --git a/Make/macOS/generate b/Make/macOS/generate
--- a/Make/macOS/generate
+++ b/Make/macOS/generate
@@ -1,116 +1,336 @@
-#!/bin/sh
-# Generate the Xcode project from a template.
-# The script uses "B-Human.xcodeproj/template.pbxproj" as a template and the file
-# search patterns from "B-Human.xcodeproj/project.pbxgen" to generate
-# "B-Human.xcodeproj/project.pbxproj". Afterwards, "B-Human.xcodeproj" can then be
-# opened using Xcode. The script also installs some data formatters for the
-# Xcode debugger and a system text service for formatting B-Human's source code
-# that also handles the macros used.
-# This script can be launched from the Finder. If the git hook
-# is installed, it is also automatically called whenever git changes
-# the working copy except for cherry-picking.
+#!/bin/bash
+# Generate Xcode project using CMake. The script requires that the CMake bundle is
+# installed in a location where macOS can find it (e.g. /Applications). It runs both
+# on Intel and ARM Macs.
+
+# Set default value for using Rosetta 2. On Intel Macs, it must be empty. Otherwise,
+# CMake will complain about an unused definition.
+if [ "$(uname -m)" = arm64 ]; then
+  ROSETTA=-DROSETTA=0
+else
+  ROSETTA=
+fi
+
+# Parameter -r activates Rosetta 2 on ARM Macs.
+if [ ! -z "$ROSETTA" -a "$1" = "-r" ]; then
+  ROSETTA=-DROSETTA=1
+elif [ $# != 0 ]; then
+  echo "usage: $0 [-r]"
+  echo "  options:"
+  echo "    -r    Xcode project generates code for use with Rosetta 2 on an ARM Mac"
+  exit 1
+fi
 
 cd "$(dirname "$(which "$0")")"
 
-# Force Xcode to use Build directory
-SETTINGSFILE=WorkspaceSettings.xcsettings
-SETTINGSDIR=B-Human.xcodeproj/project.xcworkspace/xcuserdata/$USER.xcuserdatad
-SETTINGSPATH=$SETTINGSDIR/$SETTINGSFILE
+CMAKE=../../Util/Buildchain/macOS/bin/cmake
+PROJECTDIR=../../Build/macOS
+PROJECTPATH=B-Human.xcodeproj
+PROJECTSRC=$PROJECTDIR/B-Human-temp.xcodeproj
 PLIST="/usr/libexec/PlistBuddy -c"
-if [ ! -e $SETTINGSPATH ]; then
-  mkdir -p $SETTINGSDIR
-  cp ../../Util/Buildchain/macOS/$SETTINGSFILE $SETTINGSPATH
+TEMPPATH=/tmp/generate.tmp
+TEMPPATH2=/tmp/generate2.tmp
+TEMPPATH3=/tmp/generate3.tmp
+
+# Create a symbolic link to cmake.
+if [ ! -e "$CMAKE" ]; then
+  echo -n "Searching for CMake... "
+  while read file; do
+    if [ -f "$file/Contents/bin/cmake" ]; then
+      ln -sf "$file/Contents/bin/cmake" "$CMAKE"
+    fi
+  done <<<"$(/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump \
+  | grep "^[ 	]*path:" \
+  | grep "CMake" \
+  | sed -e "s%[ 	]*path: *%%" -e "s% (.*%%")"
+
+  # Could the link be created?
+  if [ -e "$CMAKE" ]; then
+    echo "Found."
+  else
+    echo "Not found."
+    exit 1
+  fi
+fi
+
+# When switching between ARM and Intel code, copied frameworks will not be updated
+# by default. Therefore, app folders are deleted to force copying frameworks again.
+if [ ! -z "$ROSETTA" -a -f "$PROJECTPATH/project.pbxproj" ]; then
+  HAD_ROSETTA=0
+  if [ -z "$(grep /macOSarm64/ "$PROJECTPATH/project.pbxproj")" ]; then
+    HAD_ROSETTA=1
+  fi
+  if [ "$ROSETTA" != "-DROSETTA=$HAD_ROSETTA" -a -d ../../Build/macOS ]; then
+    find ../../Build/macOS -name "*.app" -type d | xargs rm -r
+  fi
+fi
+
+# Temporarily create cmake files for Nao libraries.
+sed <../CMake/asmjit.cmake >../CMake/asmjitNao.cmake \
+  -e 's%asmjit %asmjitNao %g'
+sed <../CMake/CompiledNN.cmake >../CMake/CompiledNNNao.cmake \
+  -e 's%asmjit%asmjitNao%g' \
+  -e 's%CompiledNN %CompiledNNNao %g' \
+  -e 's%HDF5::HDF5%Nao::HDF5::HDF5%g'
+
+# Determine directories that do not directly contain files.
+DIRONLY="$(for dir in $(find ../../Src ../../Util/SimRobot/Src -type d); do \
+  if [ -z "$(find "$dir" -depth 1 -type f -name "[^.]*")" ]; then \
+    echo "$dir"; \
+  fi; \
+done)"
+
+# Create a dummy file in directories that do not contain one.
+while read dir; do
+  touch "$dir/DUMMY_FILE.h"
+done <<<"$DIRONLY"
+
+# Prevent cmake from considering this to be a duplicate.
+rm -f ../../Util/Buildchain/macOS/include
+
+# Move CMakeFiles to Build directory, where CMake expects them.
+# Previous cache files are saved if they exist.
+if [ -d "$PROJECTPATH/CMakeFiles" ]; then
+  mkdir -p "$PROJECTDIR"
+  if [ -e "$PROJECTDIR/CMakeFiles" ]; then
+    if [ -e "$PROJECTDIR/CMakeFiles-temp" ]; then
+      rm -r "$PROJECTDIR/CMakeFiles-temp"
+    fi
+    mv "$PROJECTDIR/CMakeFiles" "$PROJECTDIR/CMakeFiles-temp"
+  fi
+  mv "$PROJECTPATH/CMakeFiles" "$PROJECTDIR"
+fi
+
+# Create project.
+"$CMAKE" -G Xcode -S ../Common -B $PROJECTDIR $ROSETTA
+
+# Delete temporary cmake files.
+rm ../CMake/asmjitNao.cmake ../CMake/CompiledNNNao.cmake
+
+# Backwards compatibility: Remove the link to project if it exists.
+if [ -L "$PROJECTPATH" ]; then
+  rm "$PROJECTPATH"
+fi
+
+# Ensure that project directory exists.
+mkdir -p $PROJECTPATH
+
+# Move generated/updated CMakeFiles directory back here.
+mv "$PROJECTDIR/CMakeFiles" "$PROJECTPATH"
+
+# Restore cache files if they exist.
+if [ -e "$PROJECTDIR/CMakeFiles-temp" ]; then
+  mv "$PROJECTDIR/CMakeFiles-temp" "$PROJECTDIR/CMakeFiles"
+fi
+
+# Remove dummy files created before.
+while read dir; do
+  rm "$dir/DUMMY_FILE.h"
+done <<<"$DIRONLY"
+
+# Assign folders to most source groups.
+grep <$PROJECTSRC/project.pbxproj -v '/Make/Common/CMakeLists.txt' \
+| sed \
+  -e 's%B-Human-temp%B-Human%' \
+  -e 's%/Build/macOS/CMakeFiles/%/Make/macOS/B-Human.xcodeproj/CMakeFiles/%' \
+| tr '\n' '~' \
+| sed 's%\(isa = PBXGroup;~[^)]*/\* \)\(/[^*]*\)\(/[^*]*\)\( \*/,[^<]*\)<group>";%\1\2\3\4<absolute>";~			path = "\2";%g'\
+| tr '~' '\n' >$TEMPPATH2
+
+# Remove some unwanted folders and files from project tree and add options to copying frameworks.
+( sed <$TEMPPATH2 -n '/targets = (/q;p' \
+  | grep -v "/\* [^ ]*_autogen \*/,$"
+  sed <$TEMPPATH2 -n '/targets = (/,$p' ) \
+  | grep -v "ALL_BUILD \*/,$" \
+  | grep -v "DUMMY_FILE.h" \
+  | sed -e 's%\.framework \*/;%.framework */; settings = {ATTRIBUTES = (CodeSignOnCopy, RemoveHeadersOnCopy, ); };%' \
+    -e 's%\.dylib \*/;%.dylib */; settings = {ATTRIBUTES = (CodeSignOnCopy, ); };%' \
+    -e 's%make -C %make -sC %g' \
+    -e 's%[[:<:]]HEADER_SEARCH_PATHS%USER_HEADER_SEARCH_PATHS%' \
+    -e 's%USER_\(HEADER_SEARCH_PATHS = ([^,;)]*_autogen/[^,;)]*,*\)%\1); USER_HEADER_SEARCH_PATHS = (%' >$TEMPPATH
+
+# CMake generates some wrong path names.
+# This assumes that "/arm64/" is not part of the path to the B-Human directory.
+if [ "$ROSETTA" = "-DROSETTA=1" ]; then
+  sed <$TEMPPATH >$TEMPPATH2 's%/arm64/%/x86_64/%g' && mv $TEMPPATH2 $TEMPPATH
+fi
+
+touch $PROJECTPATH/project.pbxproj
+sed <$PROJECTPATH/project.pbxproj 's%[A-F0-9]\{24\}%GUID%g' | sort >$TEMPPATH2
+sed <$TEMPPATH 's%[A-F0-9]\{24\}%GUID%g' | sort >$TEMPPATH3
+if cmp -s $TEMPPATH2 $TEMPPATH3; then
+  echo "Xcode project is already up to date"
 else
-  $PLIST "Set :BuildLocationStyle CustomLocation" $SETTINGSPATH 2>/dev/null || $PLIST "Add :BuildLocationStyle string CustomLocation" $SETTINGSPATH 
-  $PLIST "Set :CustomBuildIntermediatesPath ../../Build/macOS" $SETTINGSPATH 2>/dev/null || $PLIST "Add :CustomBuildIntermediatesPath string ../../Build/macOS" $SETTINGSPATH 
+  echo "Updating Xcode project"
+
+  # Sort folders Libs.
+  for NUM in 1 2 3 4; do
+    BEFORE=$(($(grep <$TEMPPATH -Fnm $NUM '/* Libs */ =' | tail -1 | sed 's%:.*%%') + 2))
+    SIZE=$(($(tail <$TEMPPATH +$(($BEFORE + 1)) | grep -Fnm 1 ");" | sed 's%:.*%%') - 1))
+    AFTER=$(($BEFORE + $SIZE + 1))
+    (
+      head <$TEMPPATH -$BEFORE
+      tail <$TEMPPATH +$(($BEFORE + 1)) | head -$SIZE | sort -fk 2
+      tail <$TEMPPATH +$AFTER
+    ) >$TEMPPATH2 \
+    && mv $TEMPPATH2 $TEMPPATH
+  done
+  mv $TEMPPATH $PROJECTPATH/project.pbxproj
+
+  # Prepare creating schemes.
+  SCHEMEDIR=$PROJECTPATH/xcshareddata/xcschemes
+  SCHEMESRC=$PROJECTSRC/xcshareddata/xcschemes
+  mkdir -p $SCHEMEDIR
+
+  # Create the three schemes for SimRobot from the ones CMake created for SimRobot and Tests.
+  # Patch in Tests target as testable and the normal target for profiling. Disable GPU
+  # validation to suppress some output. Add unlocking of keychain as pre-build step.
+  # Deactivate some building targets.
+  SCHEMETEMPLATE=$SCHEMESRC/SimRobot.xcscheme
+  sed <$SCHEMETEMPLATE >$TEMPPATH2 \
+  -e 's%\.\./\.\./Build/macOS/B-Human-temp%../../Make/macOS/B-Human%' \
+  -e 's%debugDocumentVersioning *= *"YES"/>%debugDocumentVersioning = "YES">\
+   </ProfileAction>%' \
+  -e 's%<Testables/>%<Testables>\
+      </Testables>%'
+  (
+    sed <$TEMPPATH2 -n '/<\/Testables>/q;p'
+    echo '         <TestableReference'
+    echo '            skipped = "NO">'
+    sed <$SCHEMESRC/Tests.xcscheme -n '/BuildableReference/,/\/BuildActionEntry/{/\/BuildActionEntry/!p;};/\/BuildActionEntry/q' \
+    | sed 's%\.\./\.\./Build/macOS/B-Human-temp%../../Make/macOS/B-Human%'
+    echo "         </TestableReference>"
+    sed <$TEMPPATH2 -n '/<\/Testables>/,$p'
+  ) \
+  | (
+    sed -n '/<\/ProfileAction>/q;p'
+    sed <$TEMPPATH2 -n '/BuildableProductRunnable/,/\/BuildableProductRunnable/p;/\/BuildableProductRunnable/q'
+    sed <$TEMPPATH2 -n '/<\/ProfileAction>/,$p'
+  ) \
+  | sed >$TEMPPATH \
+    -e 's%launchStyle *= *"0"%launchStyle = "0"\
+      enableGPUValidationMode = "1"%' \
+    -e 's%<BuildActionEntries>%<PreActions>\
+         <ExecutionAction\
+            ActionType = "Xcode.IDEStandardExecutionActionsCore.ExecutionActionType.ShellScriptAction">\
+            <ActionContent\
+               title = "Unlock Keychain"\
+               scriptText = "security unlock-keychain -p nao B-Human_Code_Release.keychain">\
+            </ActionContent>\
+         </ExecutionAction>\
+      </PreActions>\
+      <BuildActionEntries>%' \
+    -e 's%buildForTesting *= *"YES"%buildForTesting = "NO"%' \
+    -e 's%buildForArchiving *= *"YES"%buildForArchiving = "NO"%' \
+    -e 's%buildConfiguration *= *".*"%buildConfiguration = "Debug"%'
+  mv $TEMPPATH "$SCHEMEDIR/SimRobot - Debug.xcscheme"
+  sed <"$SCHEMEDIR/SimRobot - Debug.xcscheme" >$TEMPPATH 's%buildConfiguration *= *"Debug"%buildConfiguration = "Develop"%'
+  mv $TEMPPATH "$SCHEMEDIR/SimRobot - Develop.xcscheme"
+  sed <"$SCHEMEDIR/SimRobot - Debug.xcscheme" >$TEMPPATH 's%buildConfiguration *= *"Debug"%buildConfiguration = "Release"%'
+  mv $TEMPPATH "$SCHEMEDIR/SimRobot - Release.xcscheme"
+
+  # Create two schemes for the bush from the one CMake created.
+  # Disable GPU validation to suppress some output. Deactivate some building targets.
+  for PROJECT in bush; do
+    SCHEMETEMPLATE=$SCHEMESRC/$PROJECT.xcscheme
+    sed <$SCHEMETEMPLATE >$TEMPPATH2 \
+    -e 's%\.\./\.\./Build/macOS/B-Human-temp%../../Make/macOS/B-Human%' \
+    -e 's%debugDocumentVersioning *= *"YES"/>%debugDocumentVersioning = "YES">\
+   </ProfileAction>%'
+    (
+      sed <$TEMPPATH2 -n '/<\/ProfileAction>/q;p'
+      sed <$TEMPPATH2 -n '/BuildableProductRunnable/,/\/BuildableProductRunnable/p;/\/BuildableProductRunnable/q'
+      sed <$TEMPPATH2 -n '/<\/ProfileAction>/,$p'
+    ) \
+    | sed >$TEMPPATH \
+      -e 's%launchStyle *= *"0"%launchStyle = "0"\
+      enableGPUValidationMode = "1"%' \
+      -e 's%buildForTesting *= *"YES"%buildForTesting = "NO"%' \
+      -e 's%buildForArchiving *= *"YES"%buildForArchiving = "NO"%' \
+      -e 's%buildConfiguration *= *".*"%buildConfiguration="Debug"%'
+    mv $TEMPPATH "$SCHEMEDIR/$PROJECT - Debug.xcscheme"
+    sed <"$SCHEMEDIR/$PROJECT - Debug.xcscheme" >$TEMPPATH 's%buildConfiguration *= *"Debug"%buildConfiguration = "Release"%'
+    mv $TEMPPATH "$SCHEMEDIR/$PROJECT - Release.xcscheme"
+  done
+
+  # Create three schemes for Nao from the one CMake created.
+  # Set the deployDialog as runnable target. Deactivate some building targets.
+  SCHEMETEMPLATE=$SCHEMESRC/Nao.xcscheme
+  sed <$SCHEMETEMPLATE >$TEMPPATH \
+  -e 's%\.\./\.\./Build/macOS/B-Human-temp%../../Make/macOS/B-Human%' \
+  -e 's%selectedDebuggerIdentifier.*%selectedDebuggerIdentifier = ""%' \
+  -e 's%selectedLauncherIdentifier.*%selectedLauncherIdentifier = "Xcode.IDEFoundation.Launcher.PosixSpawn"%' \
+  -e 's%buildForTesting *= *"YES"%buildForTesting = "NO"%' \
+  -e 's% buildForProfiling *= *"YES"% buildForProfiling = "NO"%' \
+  -e 's%buildForArchiving *= *"YES"%buildForArchiving = "NO"%' \
+  -e 's%buildConfiguration *= *".*"%buildConfiguration = "Debug"%'
+  mv $TEMPPATH "$SCHEMEDIR/Nao - Debug.xcscheme"
+  sed <"$SCHEMEDIR/Nao - Debug.xcscheme" >$TEMPPATH \
+    -e 's%buildConfiguration *= *"Debug"%buildConfiguration = "Develop"%' \
+    -e 's%argument *= *"Debug"%argument = "Develop"%'
+  mv $TEMPPATH "$SCHEMEDIR/Nao - Develop.xcscheme"
+  sed <"$SCHEMEDIR/Nao - Debug.xcscheme" >$TEMPPATH \
+    -e 's%buildConfiguration *= *"Debug"%buildConfiguration = "Release"%' \
+    -e 's%argument *= *"Debug"%argument = "Release"%'
+  mv $TEMPPATH "$SCHEMEDIR/Nao - Release.xcscheme"
+
+  # Delete files that are invalid after the project was regenerated.
+  find -E ../../Build/macOS -regex ".*-[A-F0-9]*\.(d|dia|o)" | xargs rm
+
+  # Avoid automatically creating schemes for all targets.
+  SETTINGSDIR=$PROJECTPATH/project.xcworkspace/xcshareddata
+  SETTINGSPATH=$SETTINGSDIR/WorkspaceSettings.xcsettings
+  mkdir -p $SETTINGSDIR
+  mv $PROJECTSRC/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings $SETTINGSPATH
+  $PLIST "Set :IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded false" $SETTINGSPATH
+
+  # Force Xcode to use Build directory.
+  SETTINGSDIR=$PROJECTPATH/project.xcworkspace/xcuserdata/$USER.xcuserdatad
+  SETTINGSPATH=$SETTINGSDIR/WorkspaceSettings.xcsettings
+  mkdir -p "$SETTINGSDIR"
+  $PLIST "Set :BuildLocationStyle CustomLocation" $SETTINGSPATH >/dev/null 2>>/dev/null || $PLIST "Add :BuildLocationStyle string CustomLocation" $SETTINGSPATH  >/dev/null
+  $PLIST "Set :CustomBuildIntermediatesPath ../../Build/macOS" $SETTINGSPATH 2>/dev/null || $PLIST "Add :CustomBuildIntermediatesPath string ../../Build/macOS" $SETTINGSPATH
   $PLIST "Set :CustomBuildLocationType RelativeToWorkspace" $SETTINGSPATH 2>/dev/null || $PLIST "Add :CustomBuildLocationType string RelativeToWorkspace" $SETTINGSPATH
   $PLIST "Set :CustomBuildProductsPath ../../Build/macOS" $SETTINGSPATH 2>/dev/null || $PLIST "Add :CustomBuildProductsPath string ../../Build/macOS" $SETTINGSPATH
   $PLIST "Set :DerivedDataLocationStyle Default" $SETTINGSPATH 2>/dev/null || $PLIST "Add :DerivedDataLocationStyle string Default" $SETTINGSPATH
 fi
 
-# Create list of schemes that hides the default ones
-SETTINGSFILE=xcschememanagement.plist
-SETTINGSDIR=B-Human.xcodeproj/xcuserdata/$USER.xcuserdatad/xcschemes
-SETTINGSPATH=$SETTINGSDIR/$SETTINGSFILE
-if [ ! -e $SETTINGSPATH ]; then
-  mkdir -p $SETTINGSDIR
-  cp ../../Util/Buildchain/macOS/$SETTINGSFILE $SETTINGSPATH
-fi
-
-# Disable App Nap for SimRobot
+# Disable App Nap for SimRobot.
 defaults write org.B-Human.SimRobot NSAppSleepDisabled -bool YES
 
-# Install data formatters for Xcode debugger
+# Install data formatters for Xcode debugger.
 if [ ! -e ~/Library/Developer/Xcode/UserData/Debugger/CustomDataFormatters ]; then
   mkdir -p ~/Library/Developer/Xcode/UserData/Debugger/
-  ln -fs "`pwd`/../../Util/Buildchain/macOS/CustomDataFormatters" ~/Library/Developer/Xcode/UserData/Debugger/
+  ln -sf "`pwd`/../../Util/Buildchain/macOS/CustomDataFormatters" ~/Library/Developer/Xcode/UserData/Debugger/
 fi
 
-# Install AStyle for B-Human service
+# Install AStyle for B-Human service.
 mkdir -p ~/Library/Services/AStyle\ for\ B-Human.workflow/Contents/
 cp ../../Util/Buildchain/macOS/AStyle\ for\ B-Human.workflow/Contents/Info.plist ~/Library/Services/AStyle\ for\ B-Human.workflow/Contents/
 sed <../../Util/Buildchain/macOS/AStyle\ for\ B-Human.workflow/Contents/document.wflow >~/Library/Services/AStyle\ for\ B-Human.workflow/Contents/document.wflow "s%PWD%`pwd`%"
 
-# Install certificate for app signing
+# Install certificate for app signing.
 cp ../../Util/Buildchain/macOS/B-Human_Code_Release.keychain-db ~/Library/Keychains/
 security find-certificate -c B-Human_Code_Release >/dev/null 2>/dev/null
 if [ ! $? = 0 ]; then
   security list-keychains -s `security list-keychains | tr '\n' ' ' | tr '\"' ' '` B-Human_Code_Release.keychain-db
 fi
 
-# Set link for address sanitizer
-rm -f ../../Util/Buildchain/macOS/lib
-ln -s "$(dirname "$(dirname "$(xcrun -find clang++)")")/lib" ../../Util/Buildchain/macOS/lib
+# Set link to clang++ and its headers.
+CLANGLIBPATH="$(dirname "$(dirname "$(xcrun -find clang++)")")/lib"
+ln -sf "$CLANGLIBPATH" ../../Util/Buildchain/macOS
+CLANGINCLUDEPATH="$(ls -d "$CLANGLIBPATH"/clang/*/include | head -1)"
+ln -sf "$CLANGINCLUDEPATH" ../../Util/Buildchain/macOS
 
-# Link file templates
+# Link file templates.
 mkdir -p ~/Library/Developer/Xcode/Templates/
 rm -f ~/Library/Developer/Xcode/Templates/B-Human
 ln -s "`pwd`/../../Util/BuildChain/macOS/templates" ~/Library/Developer/Xcode/Templates/B-Human
 
-# Copy code snippets
+# Copy code snippets.
 mkdir -p ~/Library/Developer/Xcode/UserData/CodeSnippets
 rsync -u ../../Util/BuildChain/macOS/snippets/*.codesnippet ~/Library/Developer/Xcode/UserData/CodeSnippets/
 
-# Generate project file
-if [ "$1" == "-b" ]; then
-  export EXE=../../../Util/Buildchain/macOS/bin/pbxgen
-  export CFG=project.pbxgen
-  export SRC=project.pbxproj
-  export DST=template.pbxproj
-  export MSG=template
-  cd B-Human.xcodeproj
-  shift
-else
-  export EXE=../../Util/Buildchain/macOS/bin/pbxgen
-  export CFG=B-Human.xcodeproj/project.pbxgen
-  export SRC=B-Human.xcodeproj/template.pbxproj
-  export DST=B-Human.xcodeproj/project.pbxproj
-  export MSG=project
-fi
-
-if [ "$1" == "-p" ]; then
-  export ECHO="read -p"
-else
-  export ECHO=echo
-fi
-
-$EXE $CFG $SRC
-
-# Activate AVX2 in project if available and set macOS version or filter them out of the template
-if [ "$MSG" == "template" ]; then
-  sed <$SRC.tmp >$SRC.tmp2 \
-  -e "s%CLANG_X86_VECTOR_INSTRUCTIONS = avx2%CLANG_X86_VECTOR_INSTRUCTIONS = default%" \
-  && mv $SRC.tmp2 $SRC.tmp
-else
-  AVX=default
-  ( sysctl -a | grep AVX2 >/dev/null ) && AVX=avx2
-  sed <$SRC.tmp >$SRC.tmp2 \
-  -e "s%CLANG_X86_VECTOR_INSTRUCTIONS = default%CLANG_X86_VECTOR_INSTRUCTIONS = $AVX%" \
-  && mv $SRC.tmp2 $SRC.tmp
-fi
-
-# Overwrite current file with the newly generated one if they differ (Xcode will reload the project).
-if [ -e $SRC.tmp ]; then
-  cmp -s $SRC.tmp $DST || ( mv $SRC.tmp $DST && $ECHO "Xcode $MSG changed." )
-  rm -f $SRC.tmp
-fi
+# Cleanup.
+rm -r $PROJECTSRC
+rm -f $TEMPPATH $TEMPPATH2 $TEMPPATH3
