CodeRelease 2018

diff --git a/Install/installRobot b/Install/installRobot
--- a/Install/installRobot
+++ b/Install/installRobot
@@ -2,8 +2,7 @@
 
 set -eu
 
-scriptPath="$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")"
-baseDir="$(dirname "${scriptPath}")"
+baseDir="$(cd "$(dirname "$(which "$0")")" && pwd)"
 bhDir="$(dirname "${baseDir}")"
 includeDir="${baseDir}/Include/"
 
@@ -27,7 +26,7 @@ parseOptions() {
     if [ $# -gt 1 ] ; then
       error "Too many arguments!"
     fi
-	usage
+    usage
   fi
   robotIp=${1}
 
@@ -43,20 +42,20 @@ getNames() {
   if [ ! -f "${robotsFile}" ]; then
     fatal "The file ${robotsFile} (containing the robot names and ids) does not exist!"
   fi
-  
+
   # copy python scripts
   tmpPath="/tmp/NaoInstall"
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "rm -Rf ${tmpPath}" || fatal "Can't remove '${tmpPath}' on NAO"
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "mkdir -p ${tmpPath}" || fatal "Can't create '${tmpPath}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/bin/getHeadId.py" nao@${robotIp}:${tmpPath}/getHeadId.py || fatal "Can't copy 'getHeadId.py' to NAO"
-  
+
   # get headId
   local headId
-  headId=$(ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "python /tmp/NaoInstall/getHeadId.py | grep -v '[I]'")
+  headId=$(ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "bash -l -c 'python /tmp/NaoInstall/getHeadId.py' | grep -vE '\[(W|I)\]'")
   if [ ${headId} == "Fail" ]; then
     fatal "Failed reading the headId!"
   fi
-  
+
   #find robotName
   grepForHeadId=$(grep ${headId} "${robotsFile}")
   numOfMatchingHeadIds=$(echo "${grepForHeadId}" | wc -l)
@@ -66,11 +65,11 @@ getNames() {
     fatal "${robotsFile} contains the headId \"${headId}\" more than once!"
   else
     robotName=$(echo "${grepForHeadId}" | sed "s%.*name[	 ]*=[	 ]*\"\([^\"]*\).*%\1%")
-	if [ ${robotName} == "" ]; then
-	  fatal "RobotName is empty"
-	fi
+    if [ ${robotName} == "" ]; then
+      fatal "RobotName is empty"
+    fi
   fi
-  
+
   robotDir="${baseDir}/Robots/${robotName}"
 
   # does the robot exist?
@@ -91,14 +90,14 @@ copyFiles() {
     message "Buggy Ethernet driver detected! Limiting bandwidth to 100 kb/s"
     rsyncOptions="${rsyncOptions} --bwlimit=100"
   fi
-  
+
   copyTo="/tmp/NaoInstall/${robotName}"
   message "Copying files to ${copyTo}"
   if [[ $(uname) == "*CYGWIN*" ]] ; then
     chmod -R 755 "${fileDir}"
     setfacl -s d:u::rwx,d:g::r-x,d:o:r-x "${fileDir}" #due to windows 8
   fi
-  
+
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "mkdir -p ${copyTo}" || fatal "Can't create '${copyTo}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}"/* nao@${robotIp}:${copyTo} || fatal "Can't copy to '${copyTo}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${robotDir}"/* nao@${robotIp}:${copyTo}/Robot/ || fatal "Can't copy to '${copyTo}/Robot' on NAO"
@@ -107,7 +106,7 @@ copyFiles() {
 
 runInstallation() {
   message "launching install process"
-  ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "chmod -R 755 ${copyTo} && ${copyTo}/install" || fatal "Installation failed"
+  ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "chmod -R 755 ${copyTo} && bash -l -c '${copyTo}/install'" || fatal "Installation failed"
 }
 
 ###############################################################################
diff --git a/Make/Common/copyfiles b/Make/Common/copyfiles
--- a/Make/Common/copyfiles
+++ b/Make/Common/copyfiles
@@ -30,17 +30,17 @@ usage()
 
 copy()
 {
-  REMOTE=$1
+  REMOTE=`$RESOLVE <<<"$1"`
   PLAYER=$2
 
   if [ ! -z $PLAYER ] && ( (( $PLAYER < 1 )) || (( $PLAYER > 6 )) ); then
-    echo "Error: Player number is $PLAYER!"
+    echo "error: player number is $PLAYER!" >&2
     exit 1
   fi
 
   if [ ! -z $CHECK ]; then
     if [ `ping ${pingoptions} $REMOTE >/dev/null && echo 1 || echo 0` = "0" ]; then
-      echo "$REMOTE not reachable"
+      echo "$REMOTE not reachable" >&2
       exit 1
     fi
   fi
@@ -79,7 +79,7 @@ copy()
   fi
 
   echo "updating bhuman"
-  rsync --del --exclude=.* --exclude=/Images --exclude=/Logs --exclude=/Scenes --exclude=/Keys --exclude=libbhuman.so --exclude=libgamectrl.so --chmod=u+rw,go+r,Dugo+x -rzce "ssh $sshoptions" ../../Build/Linux/$COMPONENT/$CONFIG/bhuman ../../Config/. nao@$REMOTE:/home/nao/Config
+  rsync --del --exclude=.* --exclude=/Images --exclude=/Keys --exclude=/Logs --exclude=/Scenes --exclude=/Statistics --exclude=libbhuman.so --exclude=libgamectrl.so --chmod=u+rw,go+r,Dugo+x -rzce "ssh $sshoptions" ../../Build/Linux/$COMPONENT/$CONFIG/bhuman ../../Config/. nao@$REMOTE:/home/nao/Config
 
   echo "updating libs"
   RESULT=`rsync --chmod=u+rw,go+r,Dugo+x --stats -zce "ssh $sshoptions" ../../Build/Linux/libbhuman/$CONFIG/libbhuman.so ../../Build/Linux/libgamectrl/$CONFIG/libgamectrl.so nao@$REMOTE:/home/nao/Config`
@@ -100,19 +100,6 @@ copy()
 
   #reset capture volume to 100%
   ssh $sshoptions nao@$REMOTE "amixer set Capture 100% unmute &> /dev/null"
-
-  #check if magic number is too big
-  if [ ! -z $MAGICNUMBER ]; then
-    if [ $MAGICNUMBER -gt 255 ]; then
-      MAGICNUMBER=255
-    fi
-    #calculate random magic number
-    if [ $MAGICNUMBER -le -1 ]; then
-      MAGICNUMBER=$(awk 'BEGIN{srand();print int(rand()*255) }')
-    fi
-
-    echo "setting magic number to $MAGICNUMBER"
-  fi
 
   # set settings on robot
   if [ ! -z $SCENARIO ] || [ ! -z $LOCATION ] || [ ! -z $TEAM ] || [ ! -z $PORT ] || [ ! -z $PLAYER ] || [ ! -z $NUMBER ] || [ ! -z $MAGICNUMBER ]; then
@@ -145,12 +132,10 @@ copy()
 
 set -e
 
-scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
-basePath=$(dirname "${scriptPath}")
-currPath=$(pwd)
 keySource=../../Config/Keys/id_rsa_nao
 keyFile=/tmp/id_rsa_nao
-sshoptions="-c arcfour -i $keyFile -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"
+cipher=`( ssh -Q cipher | grep "arcfour"; echo "aes128-ctr" ) | head -1`
+sshoptions="-c $cipher -i $keyFile -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"
 if [[ $(uname) == *CYGWIN* ]]; then
   pingoptions="-w 1 -n 1"
 elif [ $(uname) == "Darwin" ]; then
@@ -159,7 +144,7 @@ else
   pingoptions="-w 1 -c 1"
 fi
 
-cd "${basePath}"
+cd "$(dirname "$(which "$0")")"
 cp $keySource $keyFile
 
 # init variables
@@ -174,6 +159,7 @@ REMOTE=
 COMPILE=1
 CHECK=1
 NUMMULTIPLE=0
+RESTART=
 RESTARTNAOQI=
 STOPNAOQI=
 MULTIPLEDATA=
@@ -182,6 +168,12 @@ VOLUME=100
 PROFILE=
 PORT=
 MAGICNUMBER=
+if [ -z "$(ls 2>/dev/null ../../Config/Robots/*/network.cfg)" ]; then
+  RESOLVE=cat
+else
+  RESOLVE=`echo "sed"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^lan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\1/\2/%"; ls ../../Config/Robots/*/network.cfg | xargs grep -H "^wlan" | sed "s%.*/\(.*\)/.*\"\(.*\)\";.*%-e s/\1/\2/%" | tr '[:upper:]' '[:lower:]'`
+  RESOLVE=`tr '\n' ' ' <<<"$RESOLVE"`
+fi
 
 # parse options
 [ "x" = "x$*" ] && usage
@@ -231,7 +223,6 @@ while true; do
       ;;
     "-d" | "/d")
       DELETELOGS=1
-      RESTART=1
       ;;
     "-h" | "/h" | "/?" | "--help")
       usage
@@ -268,7 +259,7 @@ while true; do
       CONFIG="Debug"
       ;;
     -*)
-      echo "unknown parameter: $1"
+      echo "unknown parameter: $1" >&2
       usage
       ;;
     *)
@@ -281,12 +272,12 @@ done
 if [ ! -z $SCENARIO ]; then
   if [ "$(ls ../../Config/Scenarios/ | grep ${SCENARIO})" == "" ]; then
     if [ "$(ls ../../Config/Scenarios/ | grep -i ${SCENARIO})" != "" ]; then
-      echo "Scenario $SCENARIO is not present"
-      LOCATION="$(ls ../../Config/Scenarios/ | grep -i ${SCENARIO})"
+      echo "Scenario $SCENARIO is not present" >&2
+      SCENARIO="$(ls ../../Config/Scenarios/ | grep -i ${SCENARIO})"
       echo "Did you mean $SCENARIO?"
       echo "Now using $SCENARIO"
     else
-      echo "Scenario \"$SCENARIO\" is not present"
+      echo "Scenario \"$SCENARIO\" is not present" >&2
       exit 1
     fi
   fi
@@ -295,15 +286,37 @@ fi
 if [ ! -z $LOCATION ]; then
   if [ "$(ls ../../Config/Locations/ | grep ${LOCATION})" == "" ]; then
     if [ "$(ls ../../Config/Locations/ | grep -i ${LOCATION})" != "" ]; then
-      echo "Location $LOCATION is not present"
+      echo "Location $LOCATION is not present" >&2
       LOCATION="$(ls ../../Config/Locations/ | grep -i ${LOCATION})"
       echo "Did you mean $LOCATION?"
       echo "Now using $LOCATION"
     else
-      echo "Location \"$LOCATION\" is not present"
+      echo "Location \"$LOCATION\" is not present" >&2
       exit 1
     fi
   fi
+fi
+
+# check if magic number is too big
+if [ ! -z $MAGICNUMBER ]; then
+  if [ $MAGICNUMBER -gt 255 ]; then
+    MAGICNUMBER=255
+  fi
+  # calculate magic number from ip if -1
+  if [ $MAGICNUMBER -le -1 ]; then
+    if [[ $(uname) == *CYGWIN* ]]; then
+      MAGICNUMBER=$(ipconfig | grep -e "${REMOTE%.*}" | head -n 1 | sed "s%.*\.%%")
+    else      
+      MAGICNUMBER=$(ifconfig 2>/dev/null \
+                    | grep -e "${REMOTE%.*}" \
+                    | sed "s%.*\.\([0-9]*\)  *netmask.*%\1%")
+    fi
+    if [ -z "$MAGICNUMBER" ]; then
+      echo "error: cannot generate magic number (set one other than -1)."
+      exit 1
+    fi
+  fi
+  echo "setting magic number to $MAGICNUMBER"
 fi
 
 #key may only be accessed by the owner. Otherwise ssh will complain
@@ -314,16 +327,16 @@ if [ ! -z $COMPILE ]; then
     # macOS
     ./compile $COMPONENT $CONFIG
     [ $? -ne 0 ] && exit 1
-  elif [ -z "${ComSpec}${COMSPEC}" ]; then
-    # Linux
-    make $COMPONENT CONFIG=$CONFIG
-    [ $? -ne 0 ] && exit 1
-  else
+  elif [ "$OSTYPE" = "cygwin" -o "$OSTYPE" = "msys" -o -e /proc/version -a ! -z "`grep Microsoft </proc/version`" ]; then
     # Windows
     echo "------ Compiling $COMPONENT ($CONFIG) ------"
     ../../Util/SimRobot/Util/mare/Windows/bin/mare.exe ${COMPONENT} CONFIG=${CONFIG}
     [ $? -ne 0 ] && exit 1
     echo "------ Successfully compiled ------"
+  else
+    # Linux
+    make $COMPONENT CONFIG=$CONFIG
+    [ $? -ne 0 ] && exit 1
   fi
 fi
 
@@ -337,9 +350,6 @@ else # try to deploy to multiple targets
     done
     wait
   else
-    cd "${currPath}"
     exit 1
   fi
 fi
-
-cd "${currPath}"
diff --git a/Make/Hooks/installHooks b/Make/Hooks/installHooks
--- a/Make/Hooks/installHooks
+++ b/Make/Hooks/installHooks
@@ -1,17 +1,18 @@
 #!/bin/bash
 
-scriptname=$0
-scriptDir="`dirname $0`"
+scriptDir=$(cd "$(dirname "$(which "$0")")" && pwd)
 
 usage() {
   echo "Usage:"
-  echo "    $scriptname [-g] [-t] [-f] [repo]..."
+  echo "    $0 [-g] [-t] [-f] [-p <path>] [repo]..."
   echo ""
   echo "  -g        Do not enable generate hooks in the git config (per repo)"
   echo ""
   echo "  -t        Do not enable pre-commit hook (checkTab, per repo)"
   echo ""
   echo "  -f        Overwrite existing files"
+  echo ""
+  echo "  -p <path> Specifiy path to git executable"
   echo ""
   echo "  repo...   Repos where the hooks should be installed"
   echo "            (default: \`$scriptDir/../..\`)"
@@ -31,15 +32,27 @@ files="generate.sh post-checkout post-merge post-rewrite pre-commit"
 enableGenerate=1
 enableCheckTabs=1
 force=0
+git=git
 
-while getopts ":gtf" option
+while getopts ":gtfp:" option
 do
   case $option in
-    g)    enableGenerate=0;;
-    t)    enableCheckTabs=0;;
-    f)    force=1;;
-    *)    usage
-          exit 1;;
+    g)
+      enableGenerate=0
+      ;;
+    t)
+      enableCheckTabs=0
+      ;;
+    f)
+      force=1
+      ;;
+    p)
+      git="`tr '\\\' '/' <<<"$OPTARG"`"
+      ;;
+    :|*)
+      usage
+      exit 1
+      ;;
   esac
 done
 shift $(($OPTIND-1))
@@ -57,29 +70,43 @@ then
   printf " enableGenerate: %b\n" $enableGenerate
   printf "enableCheckTabs: %b\n" $enableCheckTabs
   printf "          force: %b\n" $force
+  printf "           path: %s\n" $git
+fi
+
+gitFromGit="$git"
+
+if [ -e /proc/version -a ! -z "`grep Microsoft </proc/version`" ]; then
+  git=`echo "$git" | sed 's%^\([A-Za-z]\)\:/\(.*\)%/mnt/\L\1\E/\2%'`
+fi
+
+if [ -z "`"$git" 2>/dev/null`" ]; then
+  echo "Error: '$git' not found" >&2
+  echo "  Use -p <path> to specify path to git binary" >&2
+  exit 1
 fi
 
 for d in $installDIRs
 do
   ad="$(absolute "$d")"
   echo "Install to $ad"
+  mkdir -p "$ad/.git/hooks"
   for f in $files
   do
     if [[ -e "$ad/.git/hooks/$f" && $force -ne 1 ]]
     then
-      echo "Skipping $f since it already exists"
+      echo "Warning: Skipping $f since it already exists"
       echo "  Use -f to overwrite existing files"
     else
-      cp "$scriptDir/$f" "$ad/.git/hooks/$f"
+      sed <"$scriptDir/$f" >"$ad/.git/hooks/$f" "s%'GIT'%'$gitFromGit'%g"
     fi
   done
   cd "$ad"
   if [ $enableGenerate -eq 1 ]
   then
-    git config hooks.generateProject true
+    "$git" config hooks.generateProject true
   fi
   if [ $enableCheckTabs -eq 1 ]
   then
-    git config hooks.checkTabs true
+    "$git" config hooks.checkTabs true
   fi
 done
