CodeRelease 2017

diff --git a/Install/Include/bhumanBase b/Install/Include/bhumanBase
--- a/Install/Include/bhumanBase
+++ b/Install/Include/bhumanBase
@@ -11,7 +11,8 @@ export makeDir="${bhDir}/Make/"
 
 export robotsFile="${configDir}/Robots/robots.cfg"
 
-export privateKey="${configDir}/Keys/id_rsa_nao"
+export privateKeySource="${configDir}/Keys/id_rsa_nao"
+export privateKey=/tmp/id_rsa_nao
 export sshOptions="-c arcfour -o PreferredAuthentications=publickey,keyboard-interactive -o NumberOfPasswordPrompts=1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"
 if [ `uname` = Darwin ]; then
   export rsyncOptions="-qzPha --delete"
@@ -123,12 +124,14 @@ robotsIds = [
 # $1: The robotIp
 copyKey() {
   message "Copying authorized keys. If prompted please enter password twice (usually nao)."
+  cp "${privateKeySource}" "${privateKey}"
   chmod 600 "${privateKey}"
-  chmod 600 "${fileDir}/authorized_keys"
+  cp "${fileDir}/authorized_keys" /tmp/authorized_keys
+  chmod 600 "/tmp/authorized_keys"
   if [[ $(uname) == "*CYGWIN*" ]] ; then
     which setfacl >/dev/null && setfacl -s u::rw-,g::---,o:--- "${privateKey}" #due to windows 8
-    which setfacl >/dev/null && setfacl -s u::rw-,g::---,o:--- "${fileDir}/authorized_keys" #due to windows 8
+    which setfacl >/dev/null && setfacl -s u::rw-,g::---,o:--- "/tmp/authorized_keys" #due to windows 8
   fi
-  ssh -i "${privateKey}" ${sshOptions} nao@${1} "mkdir -p .ssh && chmod -R 700 .ssh"
-  rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/authorized_keys" nao@${1}:.ssh/authorized_keys
+  ssh -i "${privateKey}" ${sshOptions} nao@${1} "mkdir -p .ssh && chmod -R 700 .ssh" || fatal "Can't change access rights on NAO's '.ssh' folder"
+  rsync ${rsyncOptions} -e "${sshCommand}" "/tmp/authorized_keys" nao@${1}:.ssh/authorized_keys || fatal "Can't copy 'authorized_keys' to NAO"
 }
diff --git a/Install/createRobot b/Install/createRobot
--- a/Install/createRobot
+++ b/Install/createRobot
@@ -22,7 +22,7 @@ profilesOnly=""
 usage() {
   echo "usage:"
   echo "${0} [-h]"
-  echo "${0} [-d] -t <teamID> -r <robotPart> <name>"
+  echo "${0} [-p] [-d] -t <teamID> -r <robotPart> <name>"
   echo "${0} -D <name>"
   echo ""
   echo " <name>     : name of the robot"
@@ -189,6 +189,11 @@ if [ -n "${profilesOnly}" ]; then
   
   if ! createProfiles; then
     error "Failed to create network profiles"
+    fatal "Rerun ${0} with -d"
+  fi
+
+  if ! createBushConfig; then
+    error "Failed to create configuration for the bush"
     fatal "Rerun ${0} with -d"
   fi
 else
diff --git a/Make/Linux/login b/Make/Linux/login
--- a/Make/Linux/login
+++ b/Make/Linux/login
@@ -1,9 +1,20 @@
 #!/bin/sh
 scriptPath=$(echo $0 | sed "s|^\.\./|`pwd`/../|" | sed "s|^\./|`pwd`/|")
-basePath=$(dirname ${scriptPath})
+basePath=$(dirname "${scriptPath}")
 currPath=$(pwd)
 cd "${basePath}"
-echo "sc Remote $1" >../../Config/Scenes/Includes/connect.con
-chmod 400 ../../Config/Keys/id_rsa_nao
-ssh -i ../../Config/Keys/id_rsa_nao -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet nao@$1
+
+if [ "$1" = "-b" ]; then
+  # called from bush
+  shift
+  clear
+else
+  echo "sc Remote $1" >../../Config/Scenes/Includes/connect.con
+fi
+cp ../../Config/Keys/id_rsa_nao /tmp/id_rsa_nao
+chmod 600 /tmp/id_rsa_nao
+ssh -i /tmp/id_rsa_nao -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet nao@$1
+if [ $? == 255 ]; then
+  echo "Error: Cannot connect to $1" >&2
+fi
 cd "${currPath}"
